### ISSUE TITLE
Switch to <stdint.h>

### ISSUE THREAD

**Issue by devinsmith** [memecode/Lgi#2]
Currently LgiDefs.h has a lot of typedefs for various  bit-sized integers (int8, int16, and so on). Would you be open to a pull request converting this code to use <stdint.h> ? I think it should be as simple as taking the existing types and adding _t. Thoughts?

**Comment by memecode** [comment]
Sure that sounds pretty reasonable.

**Comment by devinsmith** [comment]
This seems to be a lot more work than I thought it was, and will take a significant amount of time. For that reason I'm going to close this issue. I had intended to switch things like int8 directly to int8_t in the code base rather than typedef int8_t to int8 but these changes touch nearly every file.

**Comment by memecode** [comment]
> This seems to be a lot more work than I thought it was, and will take a significant amount of time. For that reason I'm going to close this issue. I had intended to switch things like int8 directly to int8_t in the code base rather than typedef int8_t to int8 but these changes touch nearly every file.

I've pushed some changes that go a fair ways to achieving what you suggested. I added some error handling to the IDE so it would auto-rename symbols. Just keep hitting "build" and it would rename all the symbols as the error show up. Made the whole process some what automated, took less than an hour to get the whole thing (and all my apps) building again.
